// moon-texture-data:start
// Generated by scripts/build_moon_texture.py from
// assets/moon-textures/lroc_color_2k.jpg. Do not edit this block by hand.
var MOON_TEXTURE_WIDTH = 128;
var MOON_TEXTURE_HEIGHT = 64;
var MOON_TEXTURE_BASE64 =
  "0tPT0tPU1tXX2NfX1NfY1dTU1dXW1dXU1NXX2Nnb3N3e4ODg4eDg4d/e3t/f4ODf29jX2NnZ2NfW1dTT0tPU1NPT1NTU09TT0tHT" +
  "1dbW1tXW19fX2NnY2NjW1dXU1NTT0tPT09TV1dfW1tfW1dXT1dXV1dXV1NPV1tTU0tLU09TIys/NzsvIyMzNzcvCy83Ozc/Q0c/O" +
  "zMvLy8vJy87Q0NHT09HQz83Ly83MzdDR0tLR0dLS0NHQ0dLR09LT1NPV0crLysjKysrMzNDS1dXV1tXW1NTU1NTU1NTV1tjX2NnW" +
  "0dLR0M/R0c/Pz87Ozs7MzMzKzM7Ozs3Pz83Ny8rJycHCxsbI0dXR1dXT3N3e29va19LPzcvIw8LFxMXExcbHx8jSz87S1dzZ0tHO" +
  "zsvIycnMz9HQz9DO0c/MysvLzs7NzMfHzM3N0dXS0tLOzMvMzMvKysjHysnIzsrIyMrLysnHzMrJztLW19fT0M/MzMnHysnKzM/J" +
  "y8/SzMfIxMXDw8DAwcTHztDU2Nfd29za1NHNx8XHxsLAwsG/v729vL2/zePj2NTT1NDOz9bV0s3Q0dfZ0dHOz83Ny8nHwsG/vcTN" +
  "z9DT1tXb29rZ1tDPzsvNzMjGxsPDxsjGxMbCx8rKzNLS1dTT2djY1tLTz9LS1NfSztDR1dLQ0c/MyMXDxsXLyMjHx8fO09DOz9DK" +
  "zMvExMK9vr/AwsHBycfCv7y6uL3CwcTIxsLBxMrO0NLZ2dfU0s/P1dXX087S09PLyMfMzNPW1tPV08/NzszLysnFwsDCx8bExcXI" +
  "yMTDw8TGycfIyMvOz8zLzM7Ozs/T1tve3t3g19PP0s/PzMfExsjGytDOzsrKy8zMy8fFxsXFyMbCwcHBwcTIx8jIxsrMyMXFwbzC" +
  "xcTHxsXHzM3JxdDV09nc293d2dfW1tjX3unr6efi4tzY0c3Jx8TCwsS/u8DFw8XKx8PHyMfGysnMysrIyM3KzdLOy8vMzMzOztLT" +
  "0tDV3NzHwsfLyMrL1NHQzdHUy87Oy83S1dDQ0czN0M7P0cjCv7/CxsjFxcPJysvN0MzJxcfKv8PIy87V3dvPz83Ky8nFydDOydHU" +
  "1NbZ4evr7e/n29TQxbzAwL+7tbW2v8TExMbHyszM0M7S1Nbb2dLR3NvZ3d/a29bS0s/WzsrOy8rIx8TCwsXHyc/U0tLKzMzHy87L" +
  "ztbR0MvJzs3LysbGxMXCxcTAxMLFxsvMys/TztTPyMXIy83P1eLq4tza0svFwsK/v8LEycnN09DK0dbd29XMxsTAvcC9vLu9u7q9" +
  "v8XKyc3Mz9rd4Ofo7OXg597a4t7e4ePo4dnU0tTKyc3Q1tPOzMvKzM7OyMXGxsbHyMvMz9DKyMnMxr3Fxr2+v7+8vry+vbe/u7rA" +
  "w8jH0M/S0tDMy87PzsvU2djX1tbRycbGw728wcO6vr+9vrvByNTRwsC/t72+uLm8vL60tby+xs3Q09jg5ebm6u3w6+Tl6Ozr6eXi" +
  "3t7e19PS0c7Ky87Vz8nQzs7S0s7JyMbJycnNy8zW1MzLz87Iwr/BxMbBu7q+vby9ur67uMDFw8bEycnNzNDPys3QztDX08zKzcu+" +
  "u720s7Syt7m0qqOstLm4urm4ub24wr+0sri4vMG9w83Kztje3tbS19rb3ePu7uvr7enk6OTk5d7X1dTPzczOx8LHyszLyMvJyMTC" +
  "v8jI0NLIxsC8vcLBwcbK0NTQxr6/u72+vL6/ura5yMXAwMTQz8fGyMXCxMrKysfGx8bDv8G5u7Kvraejnpugop6hpJugqLK1rayz" +
  "tLK1tr3DwcHL0dvh09LSzMXFz9LR0tXZ3d7i5ufp5+zo3dnX0c7SzMPBv8LIxcLHwsXEvsLBwcnOxrq7yMTBvsG/vsbP1dbFvsLB" +
  "u7zBvry9uLa8urm6u8LJvrq1tLi4ur7ExcO+u7q2sq6pp6itqqajnpuZnqGfl5yjpamtpqaqpqulqKmvs8HO1NnO0srKxrq+zcSk" +
  "oLO8y9jb4eHe19vVz83Py8nCvru8v8DDwry+vL7Bw8C4vMS6u73GxMTHxcLCx8LGycXGw8jAxsK5vby5ura3ure3ub69trW0s6aZ" +
  "m6e6vbavrKSioZydoLC3qaqnq62ys7KusqeepKWkoJ+cnpqYmJyqtMPKzdC/uMjGwsC+tamst8HM09fZ3OLW1tvU0cvHv725usXE" +
  "vbm/vbq/v8HBvrm8trPEyMzIxsa/u7q6vMG/vcS8wcXDvsC6vMK9s7m4tLe5vb/FvrGvqJKSnKSjo5SUkpuvrrO+trKvraimtbOW" +
  "o67AuKmoqqWmq6ahnJ+doLC7vr+7xb7Aw73Lx7a+zc7R0MzQ2Nve5+HX19TNx8nCwL/Cyb+6trW5ur7Avb++vLy9u8/X08rEwMHC" +
  "y8i+vLy4ucPFyb63vLvHx7yzvLe2t7a6xr2ysayalpiWl5aYkomOlqS6ubywpK2mmY6QoJmerLe9uaylprG0qqioqKOyur2+vb63" +
  "sr+1v8S5uL27xcvIwcbT3OHe2dbX2NPT0c3Ly8jBur21tLu8v8vFvcC/yMvCzM3V18zExsfO0MC+v8O/xMXCv7m9wcS/v8TDvbu9" +
  "uLa8taanmouLjY2RkZOYmJ+ttbS4n5KSmIqIjo6XlZGWprC3samurLC0qqmjrLC4ubu9yraoqLTEvrzBvbi/xMrHys/R1NXS1tri" +
  "1dDT19zSzMTIxb26sra8xL63vsLNzsXOzdrYysPDwsLFxsbLzcnGv8jHy8m6wcnM1c/CubuztbqspqKPh4yFiIqJkIyHiqGopa6Y" +
  "hI2If4CJjYyRkJKWq7O3sbS+ta+mpLCuqayssLu8srarsLKpwMG/wcXGxcTFzcvN18/O1NLOztTY0MjJx8rLxse7uba5wLu9w8fH" +
  "x9DV1s3IyMTDxcPFztTW18zCwcjAvrq+v8DOz8K3ubeuqayroKaYg4SFhYWKh4mEmaWgpJeGf4CCg4SIjouNlJ6jrbC5trKxpJqg" +
  "qaqoqrO0vratwLm1trW+zM3Fx8fExMPM1NDY1s/TzsXKyNDIvLu+w8PIzdLNxcPBwMLDwMXC0+TY1NjNyMrGyMnU4N3TysS3wsS1" +
  "sra1usG8tra9u7eyrqici4uEgISEhoyFiImSmpuZg4aFf36BhIaPjI+Yo56hrbqpoKyol5mdopOju7O1tbe7v8C4tbS8vsLCycXF" +
  "yMbQ3+jh1NbPx8zNx83EwMPCwcHIycfKy8fJwLzBxcbR2t3Y08zDyszOztXW18zFwsG7vcK9s7S2t6+vu7+7uLW4qpiKgISEhImK" +
  "g4KFiomLj4qCiYiFgoCFh4mJiZScopisrImHj5qajZublKGyv7u3uL7OwrW2sbO3vMPLxcbEx87n8NbR29zTy9DKx8THycfBwcLF" +
  "wsLCytTQx8PF0c3SysrOyMnPysrS0s/OysbOzsC/xMW6ur69tLG0trayr7Cjjnl8gZGGf4OFhIeLioeKiYSMh4GBgYOGhoeEjpyn" +
  "maCTgouHiYyJrqymtbm/wrq7wsa5r6+9wbrBxsHEycm+xcPK0M3U1NjV0MjFwMLK0NXVwbjBxMLDzdXSzNLQz8/DxM3M1dbNz9PV" +
  "z87MyMzQycjHxcG5ucC5s7Kyu7usrZqGjpGNiIF+fYCKh4uSi4mJjoyGhoWEhYeJh4+YnaigkoqGhoSKi4CXrre8wMTJxLvDu7i2" +
  "tr3ExcPDx8/RycS3sbTDycrR1tbVxL++xMfFzb+dkLLOybnJzsjL29HQ0NC/wM/b1tHM1d7Nz87QycrAvby9xrGxwLiws7S/wbuv" +
  "lIaTjpOOf4B/foWEmZiPj4eNiYKHiYSDiZSRoKKYkKOWhYeFiIqGfoCoxsO8usHAvLK0v7a9ur7BxMvS0Mm3tbaytb3KyMjQ0tzL" +
  "vsLDv8fHmoeKqcjLvL3Bv8nX193Y29fS29vaz9LY18/LytLIx7+9wb/CxLa2tbm9vsXDwbOkko6alYOAgX59g4quqZKPhYKCjIWK" +
  "iYiHiYeToaGiqY57f4OKhoKCiKe4uruurK6ys6Wdq7SuvbzJzMrBw7qzure5t8bLx8vKycfFwcLMzsirmqC4xsS8wMrM1dfS2dTT" +
  "1dng2NTV0tHMxcnNz8fBwsPOz8rNyMHBwsK7yMTDuLKilJaBgpCBeXuAipOSkYuGiIqWj4qNjYmJiYGKqrWhh3x/go2Bg3+IpqGg" +
  "vbCxtKCVkYyOl6Oxu8bEwcK7v7q3t7a6wsXHxsPCwMnGyM7Lxsa+wry6wr7HzMzQzdDXz8rT29LVysbFxcPFysfGwsTCxNLTz8zR" +
  "ysK7urvBwcnGuLaZiIR/hXd2eX+AgYSHkouEiI6RlYuPko+RkZ+nnJWKhomGhYF+foecko+kv8u/l4uKhn99nbK7tbinr8LFsba0" +
  "r7q6vs3Ky8zFxcTKxs/Uw8XEvbzKy8vQ2drR19jNy9bVydrVwr26wsXHxsXEx8zRzMvR1NfXysK8sbi+wLy5taSQiX99fXp2eHt+" +
  "g4SPl4WLnqOioJ6gnpWVnpmLiI6diKCYg317eIOHfZ6vy8eXh4eCf4ibv7GhrI6VrbOvtbizsrvBzdTTzsrLxsfFwsTBvM3Jv9TX" +
  "09jd3u7j0M3R39fK0tDHwMHHvr/LycTEytfN0MvN0c3Jw723xcO9t7u1r5qThIGAfXV2eXuEg4uVkIeer6ezrqKhlYp7hIZ/gJKN" +
  "m4R0dXp9dXd1iJ6zxqOIg4GKtKy5tKqkkIiJjKGwvLizu7/S1dDMzdPKxsHBwLm6w73B0NXV3dfZ3tvT1Njb3dLOyMXIysrDxszI" +
  "zcfDxcXGxMPNyMHBvLrEu7e5vLzEtqechHx+fXt6fHmBlaifiZamrMW4oKCViIOVmYR7h6Gee3F1fnh3dHh+jZ67u6aaoqizq6y1" +
  "u66kmJmgo6y3u725uNPc1tHPz8/FwMC+v8O8wMXG2dTV3trZ1tTVz8/Uys3Iys/Dw9PO08zOx8jBv8LQy8jLw7/Fxry3u7680c7B" +
  "tq2WgIKGf399fIaasamRlZymo56Rk4d4m6qmpZugr6SAen92eHp6fIiWl5uyt7Ozp5qPorW7u66hqbasqLe/vMC8v9zd1tDJzc7H" +
  "xcXFw8XCwcTJ09Pa19XW183Ix83Fy9bOxMLCzc3P1dfNwMbEx7/IztTM1t7Lxca+vL3Hu726wLCOe3d6fn9+fY2alpCVm6WflYWN" +
  "gnqNoKW0sMK2pI59fHt9f4CAhZSbhoWkrqyvm6Gusbu9sZ2UoqmrxMTA0L3B2efe1MzHx8LHz8jFxb/HzcrW2czQzdrVycXGzMbY" +
  "4dDNycfM0dTb3NDKz8S4uMPN0dHS1sfCw7y+u7W6yLm/r4l+eXl8fnx6g4yLi4+TmqSijIqJkI+MnrS7yb6un4B8f36Zm4ORkIWD" +
  "fHmGmJuUq6eirK6ai3yOr7e+vMfQvcLc5uPS0c/MwcHJyMXEw8bHzcrQ08nJ0dDEw8DJztHQ0tfOyc7N0djc1NHNx7y5vsjPysfG" +
  "ysrFxMO3sbKuvsOpkoF7eH19enh+foKJjJKPjpqakpWmqZilt725ubqyrZ6GhrKyqpyDh4KAfoaSm6Kmq6qwpZKLjJm1tK+2wce5" +
  "vc7f49/Sys/J0M7ExczIyM3Nu7PHycjP0cbBxc7OzMLM1dDJzc3J0NfNxsnAvbq7v8bLzsvSysrJw7q2sq65k6isjHl3goN8fIB9" +
  "gYmNj4ePnJ6WtLa0tK+2vLe5usvLsZGar6qooIyGhIKIkoufqaaqr7Knl5Omq7G0ure3ubSzuNno5NPIyMTLxsXAxL/I2svBu73F" +
  "xdDNyMrL19PSy8zRycnLycvIxMfDxsK7ubrDxc3T0M/OzcjAwby+vLKFsLyYhnt4gH99fYSDiqKXhJCfooedr7Gzs7bGxLq7zsKh" +
  "mJ6vubyjkIaDhI6XsLKqqayvq7OllqW2trm2sLnAwLm3z+bYy8S+wsC5vb6/v8fLyM/IwszL0MnGy87a4tnNx9DMysjHw7+/vL++" +
  "xL62vMrW2tLX1dXLyMO2vr2zt7m5taiRf4iCgnyEgn+Imol/hY6kioqssaWusL26usTGyL+0pqerur2lkIaKlqXFvrSxsLi0ubqy" +
  "tcHAu7Wts8LDtq6+zsrExLu+u7a9wLzBu7rT2MbBxMrMwszU0drf1s3HxdXMyMbCvr+9trm+vLjIyNnd2t3h1tLAvK+4u7i5ure0" +
  "xKiPnY6Qj5yQgYCHhoqKi52Sj6CssK2xsrW5xsDJ08K1n5Chu7GkoZuVm6qssa+vq7O4uL2/v764srCzt7Owsra9w8PAvr64s7y/" +
  "tr6/wczMyMLVycC5vsrTzszRxMHDw8PMysfGwr22tbe9vsHHztPa1Ma6ycS1wbi3u7qvrbK3rKqXlZugqZuQhH+XpoyRj4mLlauz" +
  "sbW2wLu3uMXS06uUlaC+srCvrJOdpp6tqKm4srO6xsLGxLS3tLbBtay2vbjCwr++vb+6vby7t73BwsW/xMbGtra7wsG6wdDAtcDC" +
  "vcW+v8DCvre+vr3BxMjL0M6yl6ymv7+6u720uLW3wLSsqKKjsKifjoWRk56ZjI6IioWmtrizv7a3uLO9vMbPtaCTjrSnraCVoa+r" +
  "n6mmqbS8wsLJwMHJxL+3tLmvrsfFwcK7vL65trjCs8u6tru7uL/Qur+0urKwqre/v7y6t7K0u7q0r7K8vcDHusjNyMvSzsKkipvL" +
  "ycPIvr3Ex8zIxLaqqrCvjnx7faCdmJyajIeGjay8s6+1r7O6vbm3vsHHq6mwo7Goq5qtx7uprauvtrzBsLS9trrDz7+uq623y8bG" +
  "xJety7zAubi+ybe0srCxvsDDta+trrSrs7m2sq6zrrC8vcO5tLfCwcnBxMLAydDS0b+jsc/MzMe6u7rH3+POxL6xs6eHhoB8jJaO" +
  "mZGIiIKKnrazwbW3wMPCs7LF0sG1vrmxvLq9urS6v7mytLG1sLm2s722ubjBtqijsLe6ubu/vc3CwsDBvrzAv7m1sri0sbKtqqer" +
  "rqakrrKqrKqlqra4ysvHxMC9vLe3ucDJ0NPHuMTO0NTKw768vb3L1cK8v8aypZGIg4eVopCUlYOGio2lwMHOv8POwLa4wsrFwsi+" +
  "s7nAxcjLxcTKx7zEs66zw8a2s7azs7Kem7a0sK6sr7m5wMDBvLq8tsHAvLG2vbSxr7S0nKSmmZ6qsqaoqKKmtcXAxs7JwLa5tre6" +
  "vcXOzMC3vMzKy8nEvLu3uLi7v7e/zMO3pJKUm62WnaWtoKChtsbKy9DOx7+3tsPJvL++v7nAvbzB0NnZzs2/yMe3rLO7x8CzsLCw" +
  "sKakrKanucC9ubu3usLEvMzBs7XDtqy1p7ClpKukop+anKiyoKGorq2xv8HFvcnDtLO5vLi5vcLDurvHw8TIxb+5urW7vbe5s7i/" +
  "yLurq6Owmo6cosjIuL7P19/WzdLJwMDEzcDDxLq3uMTBvb/P4tfj1MXPwLq1vbiwsrCYorKtrq2uubu7v72yuruxsbi/tqWprcG8" +
  "o5mQraiqp5ihoZaLp6SYq42YrKuwvci+ycO4t7W3trO3uLm6vcnDwsfAwbe3vraytb20t7W1q5qorqyqp6y3vMrKztra5NbNz8jK" +
  "ycO+ubu4uLq4v8C+wMrR1dfFwLy6uLvCs6iVnqCboKGfprXFyMO7urS1s6+st7qfkq+ytrurm5uopaWZl6KkoJGpqJqtm5unp6iv" +
  "wcO7uL+8ure0tLO1s7i9vL26vb27vre6vbSxy7mwr7Cvp6e2tLaxuMLAx9HX3N3b2NXQy8i/vca+vcC/wb++u768xNHDxr66u7+5" +
  "tbOlp6aamKCenamjr77Bvry1sLq6squyuLSpsL+4s6ykoqitnZmorbWjlqeqmJGUn6Gjqau3w7exu7u3vLi3trS2tbe7vbu8vbu/" +
  "vbq6xr68raSytLi3uL3Bu7q1vsjR1dXU2N3a1tDQycXPxsbJxLq7w8XFx8jKvrG3uLOzr7C2qZycopqSnaWco6Orsb+/urW0urKx" +
  "sbe8v7/BwLOuqaKjprSspaysraOan6aZj5ajoaWlrrGuubWutLS6trKzs7GzsLS/xL/Avr3Eu7e4wLyjn7K0qqi4vL+7vr3Fx9LR" +
  "2tzQ2NPS0tTMv8fAwMa4usHBw8vPy8a7tbOztLWzsqSepqmlm5CWpaWhpKavvcCytLK7t7mvs9bXvr6+sKufnqWop6Sqsa+jn5+d" +
  "n5mTlZqcn6KlqLG1tbC2tLO7uLi2uLm6uLzDvb28u76+vri4vLi1rbClq7GyvMG8usPH0dfT1NfZ1tXRzcS5t7m6u73GzMrH0dbJ" +
  "vbexsre4u7q2maCwpqympp+fp6WupK6ytbS2tr68s7G9u720s62qtZ6arqqfnKiytqKgnaGhmZuYnJ+dpKKhrrqyubm1ub65vLy6" +
  "u7u9tb65ubm8xMi/urW0uLSyq6irsLO7wbq/wMPQ09va19/Z1dbQy8vEwr6/vcPAwsXIxb65s8C9xsOzraaYnqyTk6erqaOvua6y" +
  "sKywvcC6ta+wtLyzr7GprLOwr6qsppqkrKmpp6qZoqCanpqbnqCcoqGlrq2tur68wrrAvcLCurK0vr69ubzExbmzs7jAvbWtpKu3" +
  "uLq7ub7K0snU3NjR1c/Q2czIxcDBxMXCxcXFxcjEwLa2wr+7rqK3n5iao52ap6u3rqywr7O3rbC5ubWsr7O4u7i5q6yysa2ys6yo" +
  "nqKppJ+nrqCooJSYlZmioKSkoaamqqu2vrW6u7q8wr+5uby/wr+8v7+/vrm2vL2+va+jqri7vL2+xs3GzNfT08/TzsrPyMbDwMbJ" +
  "yMW/wMrKvrzBwbq1try4r7Wnl5Wlr66rr7Swtquuurm4usm8t7e3sri/uru9sLC1trOkpaiko6mqpaugnaeonpmcoKKho6SurKim" +
  "sLK3tre3wMTDv7q5u7++wb7Ew8vHv8C+wcrKxb3ByMK8vMbOw8nV3NLT1dHNzM3Lz8bJy8nDxcLEx8a+vsPGv73DxsfDwsqwqr26" +
  "rKSpr6ijpa64wr7D293Qxbi3sri+wcK1uLCkk56gn661tK2wraSos7KlpKKipaSmr7Gtqqersbm8uLvBw8LFw8HEwr7Ew8nN0MrJ" +
  "x8XJzM/Pzc/Mw8HFzM7LzNHd297Uy8bGysrM0c3Mx8bEv8DDw8TDxMHExsbCxL6+z87Cs6euqqyura+npLC8vcLP1NDGt7a7vcK9" +
  "tru0qaukqayur7Cqp7aqp6yxsqWlo6KkpKeqqqqrq6+1s7S6vLe8vcfAw8jEw8LByMzPzdDR0NDNx8XLzMjJxsTGz8vN2+HZ4tfL" +
  "y8vKycbLxsTBxcXEwsLBxszLzs3Mz8jCvsTMxLq6rqCrsLa7usS9uby7ur7I0MvBv8C8ubWxr6+tprGppqmsr6mvr6ioo6yxpqWo" +
  "pqqsqqafnaanrbGzuLa6u76/v7zHwsDCw8bExsvMy8vLzMjFyszLyMTBwsbKzNDZ3drY2M/Nzc3IxM3RysPBycnDxsXFytLUzdPU" +
  "z8vFxMDBvLe0sbC2xsrCv8DDxLvGxcXO3NC6uru/vbaor7u5tK6npamsq7KrnKSkpKGbn6iqqa2xr6mmqqysqq+wtb23t7W8wrzF" +
  "wMHDxMXExcbL0NXb1s/IxcHBwbvAw8LBx9DN1NHP0cnCx8HEzNHFyc3GxMfLzMnFx8nK0c3Av726vLm0uLWytLGzr6iqsrO5ubi4" +
  "vbvDx7q6wsq+trGwtb7DvbOppaWjoKChoaaroZ6ipKirrKyrsbK6vbWwr62vtba3tLW4u8HAucHBw8nMyMbK1tPQycLGv8DCv72z" +
  "uMPBy8nMz8jMx8PDxsnM0M/LztPNy8/Pz83Py8PAv7/Bv7u+urO5ubGrqrGnpKu2s660tbm2t7i8xMC9ura2try7tcPHuq2pr6yz" +
  "trq1ubGlpKWorLG1sKu1uLizrayvsK2zurq2tLe7xcLBxsfGysTAxsTAwcPJwsPEwsO+uLTDx8fU0s7HwMLLzc7TztHV0dnW3dnR" +
  "0cbJzM3Jx8XAvb/Bx8rHxcPCvLfBvq6yusC+uLy2tbrAwrmxrqqzt7e6ubi7u8LFwrq1sbm8vLnBupybqa6vsrSwr7OzsK6trq+x" +
  "sLO2ub2/w8DFwsG9vsPBwL27ury/wL/BxMK+vsDDyMfFzdXR1NPPz87O1t7b1tbQ19jT09XTzc3Gw8DBv8HCxMTEwMTNzdLRy8XH" +
  "xLq+w727u77GxMLCvr25s7S0s7K1ube4w8zGvLm5ubiztLy5q6+ysa2ws7i8u7i2uLi3t7a0srq+wsjDv7u9v76/vby/vr+8vL++" +
  "vby6vb27v8HAvsDIxMHBw8jLzMnJzM3O1tfT0NHPzcvJyMHFw767wMPGzMvIw8zU2dTLxMPGvra7uLa4t7zBv8PEw8bBvLi3ub/A" +
  "vr7AwL64ubzAvLq6v72+vru9u7m2trW3u727v8DBwL+8w8O+wb66v8bGx8nIyMLExcbFxMPAvr6+v8C+vsHDyc3Fwb+/wsLAxcvP" +
  "yszVz8jIxsK8vbq6uLy/xcjGyMbKzc3Mz83M0M7Pz83MxMDCxcbHyMS9wMbJx8fEwL6/wcPGx87RzcTEwc3JxMPBvb6+wcHAwMG/" +
  "vL3AwsDDx8XEx8bExMTGxL+/wMHBwcHExsfExcPDxsfHxsXGxsXGycvKxsjLy8nKyMXHy8rFxMfGxMTDxcfHxsbGxcTCvr3CxcbJ" +
  "yMjN1NTW09DR1dXSzcnJxsbGwcDCwcDAw76+vb+9wMTHx8vPzM/O3d7e3t/e3N3e3t/e39zZ2NbW1tTSzs7P0tHR09jb29va19XT" +
  "09TV1dXU1NXV1NfZ2dna29nY19PR1NbZ29va29va1tDOzs7Q0tHS1dna3d/g4uTl5+fk5OTo6+3u6+fn5+Ph4N7g4eLh4eDf3t3d" +
  "29vb2tre3dzc29za293f3Ns=";
// moon-texture-data:end

var MOON_TEXTURE = decodeTexture(MOON_TEXTURE_BASE64);

export function moonSurfaceAlbedo(dx, dy, z) {
  if (![dx, dy, z].every(Number.isFinite)) {
    return 0.5;
  }

  var longitude = Math.atan2(dx, z);
  var latitude = Math.asin(clamp(-dy, -1, 1));
  var textureX = ((longitude / (Math.PI * 2)) + 0.5) * MOON_TEXTURE_WIDTH;
  var textureY = (0.5 - latitude / Math.PI) * (MOON_TEXTURE_HEIGHT - 1);
  var left = Math.floor(textureX) % MOON_TEXTURE_WIDTH;
  var right = (left + 1) % MOON_TEXTURE_WIDTH;
  var top = Math.floor(textureY);
  var bottom = Math.min(MOON_TEXTURE_HEIGHT - 1, top + 1);
  var horizontalRatio = textureX - Math.floor(textureX);
  var verticalRatio = textureY - top;
  var topValue = mix(textureValue(left, top), textureValue(right, top), horizontalRatio);
  var bottomValue = mix(textureValue(left, bottom), textureValue(right, bottom), horizontalRatio);
  return mix(topValue, bottomValue, verticalRatio) / 255;
}

function decodeTexture(encoded) {
  var binary = atob(encoded);
  var values = new Uint8Array(binary.length);
  for (var index = 0; index < binary.length; index += 1) {
    values[index] = binary.charCodeAt(index);
  }
  return values;
}

function textureValue(x, y) {
  return MOON_TEXTURE[y * MOON_TEXTURE_WIDTH + x];
}

function mix(start, end, ratio) {
  return start + (end - start) * ratio;
}

function clamp(value, minimum, maximum) {
  return Math.min(maximum, Math.max(minimum, value));
}
