#!/usr/bin/env python3
"""Build or verify the compact runtime Moon texture from the tracked NASA source."""

from __future__ import annotations

import argparse
import base64
import hashlib
import sys
from pathlib import Path

try:
    import PIL
    from PIL import Image
except ModuleNotFoundError as exc:  # pragma: no cover - exercised only without tooling installed
    raise SystemExit(
        "Pillow is required. Install scripts/requirements-moon-texture.txt "
        "in a temporary virtual environment."
    ) from exc


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPOSITORY_ROOT / "assets/moon-textures/lroc_color_2k.jpg"
OUTPUT_PATH = REPOSITORY_ROOT / "backend/src/main/resources/static/moonTexture.js"

SOURCE_WIDTH = 2048
SOURCE_HEIGHT = 1024
TEXTURE_WIDTH = 128
TEXTURE_HEIGHT = 64
BASE64_CHUNK_LENGTH = 100

SOURCE_SHA256 = "f7130a1822681fa7512d7dcfd40db8c10b9ba4f06777910348698260ed7a2170"
TEXTURE_SHA256 = "ec492a4a37698ee395dfd0598a03c69497986504a0c55fc4319b48b77a8372cd"

GENERATED_START = "// moon-texture-data:start"
GENERATED_END = "// moon-texture-data:end"


class MoonTextureError(RuntimeError):
    """Raised when the tracked source or generated texture does not match its contract."""


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build_luminance_texture() -> bytes:
    if not SOURCE_PATH.is_file():
        raise MoonTextureError(f"Moon texture source is missing: {SOURCE_PATH}")

    source_bytes = SOURCE_PATH.read_bytes()
    source_sha256 = sha256(source_bytes)
    if source_sha256 != SOURCE_SHA256:
        raise MoonTextureError(
            "Moon texture source checksum changed: "
            f"expected {SOURCE_SHA256}, got {source_sha256}."
        )

    with Image.open(SOURCE_PATH) as source:
        if source.format != "JPEG":
            raise MoonTextureError(f"Moon texture source must be JPEG, got {source.format}.")
        if source.size != (SOURCE_WIDTH, SOURCE_HEIGHT):
            raise MoonTextureError(
                "Moon texture source dimensions changed: "
                f"expected {SOURCE_WIDTH}x{SOURCE_HEIGHT}, got {source.width}x{source.height}."
            )
        texture = source.convert("L").resize(
            (TEXTURE_WIDTH, TEXTURE_HEIGHT),
            Image.Resampling.LANCZOS,
        )
        texture_bytes = texture.tobytes()

    expected_length = TEXTURE_WIDTH * TEXTURE_HEIGHT
    if len(texture_bytes) != expected_length:
        raise MoonTextureError(
            f"Moon texture length must be {expected_length} bytes, got {len(texture_bytes)}."
        )

    texture_sha256 = sha256(texture_bytes)
    if texture_sha256 != TEXTURE_SHA256:
        raise MoonTextureError(
            "Generated Moon texture checksum changed: "
            f"expected {TEXTURE_SHA256}, got {texture_sha256}. "
            f"Pillow version: {PIL.__version__}."
        )
    return texture_bytes


def render_generated_block(texture_bytes: bytes) -> str:
    encoded = base64.b64encode(texture_bytes).decode("ascii")
    chunks = [
        encoded[index:index + BASE64_CHUNK_LENGTH]
        for index in range(0, len(encoded), BASE64_CHUNK_LENGTH)
    ]
    encoded_lines = []
    for index, chunk in enumerate(chunks):
        suffix = " +" if index < len(chunks) - 1 else ";"
        encoded_lines.append(f'  "{chunk}"{suffix}')

    return "\n".join([
        GENERATED_START,
        "// Generated by scripts/build_moon_texture.py from",
        "// assets/moon-textures/lroc_color_2k.jpg. Do not edit this block by hand.",
        f"var MOON_TEXTURE_WIDTH = {TEXTURE_WIDTH};",
        f"var MOON_TEXTURE_HEIGHT = {TEXTURE_HEIGHT};",
        "var MOON_TEXTURE_BASE64 =",
        *encoded_lines,
        GENERATED_END,
    ])


def replace_generated_block(output_text: str, generated_block: str) -> str:
    if output_text.count(GENERATED_START) != 1 or output_text.count(GENERATED_END) != 1:
        raise MoonTextureError(
            f"{OUTPUT_PATH} must contain exactly one generated Moon texture block."
        )
    start = output_text.index(GENERATED_START)
    try:
        end = output_text.index(GENERATED_END, start) + len(GENERATED_END)
    except ValueError as exc:
        raise MoonTextureError(
            f"{OUTPUT_PATH} generated Moon texture markers are out of order."
        ) from exc
    return output_text[:start] + generated_block + output_text[end:]


def run(check_only: bool) -> None:
    if not OUTPUT_PATH.is_file():
        raise MoonTextureError(f"Moon texture module is missing: {OUTPUT_PATH}")

    current_output = OUTPUT_PATH.read_text(encoding="utf-8")
    next_output = replace_generated_block(
        current_output,
        render_generated_block(build_luminance_texture()),
    )

    if check_only:
        if current_output != next_output:
            raise MoonTextureError(
                "Generated Moon texture module is stale. Run npm run moon-texture:build."
            )
        print(f"Moon texture source and generated module are current (Pillow {PIL.__version__}).")
        return

    if current_output == next_output:
        print(f"Moon texture module is already current (Pillow {PIL.__version__}).")
        return

    OUTPUT_PATH.write_text(next_output, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} (Pillow {PIL.__version__}).")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the compact runtime Moon texture from the tracked NASA SVS source."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify source integrity and generated output without writing files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        run(args.check)
    except MoonTextureError as exc:
        print(f"Moon texture error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
