import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const DEFAULT_ASSET_ROOT = new URL("../assets/moon-path-silhouettes/", import.meta.url);
const DEFAULT_MANIFEST_URL = new URL("manifest.json", DEFAULT_ASSET_ROOT);
const DEFAULT_OUTPUT_URL = new URL("../frontend/generated/moonPathSilhouetteSymbols.js", import.meta.url);

const ALLOWED_SVG_ROOT_ATTRIBUTES = new Set(["viewBox", "xmlns"]);
const ALLOWED_PATH_ATTRIBUTES = new Set(["class", "d"]);
const ALLOWED_RECT_ATTRIBUTES = new Set(["class", "height", "rx", "ry", "width", "x", "y"]);
const ALLOWED_CLASSES = new Set([
  "moon-path-foreground-hill",
  "moon-path-foreground-shape",
  "moon-path-foreground-window"
]);

const UNSAFE_SVG_PATTERNS = [
  /<\?xml/i,
  /<!doctype/i,
  /<script\b/i,
  /<foreignobject\b/i,
  /<(?:a|animate|defs|desc|embed|filter|iframe|image|lineargradient|metadata|object|radialgradient|set|style|symbol|title|use)\b/i,
  /\son[a-z]+\s*=/i,
  /\b(?:href|xlink:href)\s*=/i,
  /url\s*\(/i
];

export function buildCatalog(options = {}) {
  const manifestUrl = options.manifestUrl || DEFAULT_MANIFEST_URL;
  const assetRoot = options.assetRoot || DEFAULT_ASSET_ROOT;
  const manifest = JSON.parse(readFileSync(manifestUrl, "utf8"));
  return buildCatalogFromManifest(manifest, assetRoot, function readText(url) {
    return readFileSync(url, "utf8");
  });
}

export function buildCatalogFromManifest(manifest, assetRoot, readText) {
  if (!manifest || manifest.schemaVersion !== 1) {
    throw new Error("Silhouette manifest must use schemaVersion 1.");
  }
  if (!Array.isArray(manifest.symbols) || manifest.symbols.length === 0) {
    throw new Error("Silhouette manifest must contain at least one symbol.");
  }

  const seenIds = new Set();
  return manifest.symbols.map(function buildEntry(entry) {
    const sourceUrl = resolveAssetFile(assetRoot, entry.file, entry.id || "unknown");
    return buildSymbolRecord(entry, readText(sourceUrl), seenIds);
  });
}

export function buildSymbolRecord(entry, svgText, seenIds = new Set()) {
  validateSymbolMetadata(entry, seenIds);
  const parsed = sanitizeSvgSymbol(svgText, entry.file || entry.id);
  const baselineY = requiredPositiveNumber(entry.baselineY, entry.id + ".baselineY");
  const intrinsicHeight = requiredPositiveNumber(entry.intrinsicHeight, entry.id + ".intrinsicHeight");
  const viewBoxTop = parsed.viewBox.y;
  const viewBoxBottom = parsed.viewBox.y + parsed.viewBox.height;

  if (baselineY < viewBoxTop || baselineY > viewBoxBottom) {
    throw new Error(entry.id + " baselineY must fit inside the SVG viewBox.");
  }
  if (intrinsicHeight > baselineY - viewBoxTop) {
    throw new Error(entry.id + " intrinsicHeight must not exceed the visible height above baselineY.");
  }

  seenIds.add(entry.id);
  return {
    id: entry.id,
    viewBox: parsed.viewBox,
    baselineY: baselineY,
    intrinsicHeight: intrinsicHeight,
    tags: entry.tags.slice(),
    license: entry.license,
    attribution: entry.attribution,
    elements: parsed.elements
  };
}

export function sanitizeSvgSymbol(svgText, sourceLabel) {
  rejectUnsafeSvg(svgText, sourceLabel);

  const svgMatch = svgText.match(/^\s*<svg\b([^>]*)>([\s\S]*?)<\/svg>\s*$/i);
  if (!svgMatch) {
    throw new Error(sourceLabel + " must contain exactly one root <svg> element.");
  }

  const rootAttrs = parseAttributes(svgMatch[1], sourceLabel + " <svg>");
  rejectUnknownAttributes(rootAttrs, ALLOWED_SVG_ROOT_ATTRIBUTES, sourceLabel + " <svg>");
  const viewBox = parseViewBox(rootAttrs.viewBox, sourceLabel);
  const elements = parseSvgChildren(svgMatch[2], sourceLabel);

  if (elements.length === 0) {
    throw new Error(sourceLabel + " must contain at least one drawable element.");
  }

  return {
    viewBox: viewBox,
    elements: elements
  };
}

export function renderSymbolModule(catalog) {
  return "// Generated by scripts/build_moon_path_silhouette_symbols.mjs. Do not edit by hand.\n"
    + "// Source assets live under assets/moon-path-silhouettes/.\n\n"
    + "export var MOON_PATH_SILHOUETTE_SYMBOLS = Object.freeze("
    + JSON.stringify(catalog, null, 2)
    + ");\n";
}

async function runCli() {
  const checkOnly = process.argv.includes("--check");
  const outputUrl = DEFAULT_OUTPUT_URL;
  const nextOutput = renderSymbolModule(buildCatalog());

  if (checkOnly) {
    if (!existsSync(outputUrl)) {
      throw new Error("Generated silhouette symbol module is missing: " + fileURLToPath(outputUrl));
    }
    const currentOutput = readFileSync(outputUrl, "utf8");
    if (currentOutput !== nextOutput) {
      throw new Error("Generated silhouette symbol module is stale. Run npm run silhouettes:build.");
    }
    console.log("Silhouette symbol module is current.");
    return;
  }

  await mkdir(dirname(fileURLToPath(outputUrl)), { recursive: true });
  writeFileSync(outputUrl, nextOutput);
  console.log("Wrote " + fileURLToPath(outputUrl));
}

function validateSymbolMetadata(entry, seenIds) {
  if (!entry || typeof entry !== "object") {
    throw new Error("Silhouette symbol entry must be an object.");
  }
  if (!/^[a-z][a-z0-9-]*$/.test(entry.id || "")) {
    throw new Error("Silhouette symbol id must be lowercase kebab-case: " + String(entry.id));
  }
  if (seenIds.has(entry.id)) {
    throw new Error("Duplicate silhouette symbol id: " + entry.id);
  }
  if (!Array.isArray(entry.tags) || entry.tags.some(function invalidTag(tag) {
    return !/^[a-z][a-z0-9-]*$/.test(tag || "");
  })) {
    throw new Error(entry.id + " tags must be lowercase kebab-case strings.");
  }
  if (typeof entry.license !== "string" || entry.license.trim() === "") {
    throw new Error(entry.id + " license must be present.");
  }
  if (typeof entry.attribution !== "string" || entry.attribution.trim() === "") {
    throw new Error(entry.id + " attribution must be present.");
  }
}

function validateRelativeFile(filePath, symbolId) {
  if (typeof filePath !== "string" || filePath.trim() === "") {
    throw new Error(symbolId + " file must be present.");
  }
  if (filePath.startsWith("/")
    || filePath.includes("\\")
    || filePath.includes(":")
    || filePath.includes("%")
    || filePath.includes("?")
    || filePath.includes("#")
    || filePath.split("/").includes("..")) {
    throw new Error(symbolId + " file must stay inside the silhouette asset root.");
  }
  if (!filePath.endsWith(".svg")) {
    throw new Error(symbolId + " file must be an SVG source file.");
  }
}

function resolveAssetFile(assetRoot, filePath, symbolId) {
  validateRelativeFile(filePath, symbolId);
  const assetRootPath = fileURLToPath(assetRoot);
  const resolvedPath = resolve(assetRootPath, filePath);
  const relativePath = relative(assetRootPath, resolvedPath);

  if (relativePath === "" || relativePath.startsWith("..") || isAbsolute(relativePath)) {
    throw new Error(symbolId + " file must stay inside the silhouette asset root.");
  }
  return pathToFileURL(resolvedPath);
}

function rejectUnsafeSvg(svgText, sourceLabel) {
  UNSAFE_SVG_PATTERNS.forEach(function reject(pattern) {
    if (pattern.test(svgText)) {
      throw new Error(sourceLabel + " contains unsupported or unsafe SVG content: " + pattern);
    }
  });
}

function parseSvgChildren(childrenText, sourceLabel) {
  const elements = [];
  const tagPattern = /<(path|rect)\b([^>]*)\/>/gi;
  let cursor = 0;
  let match = tagPattern.exec(childrenText);

  while (match) {
    const gap = childrenText.slice(cursor, match.index).trim();
    if (gap !== "") {
      throw new Error(sourceLabel + " contains unsupported SVG content near: " + gap.slice(0, 40));
    }
    elements.push(sanitizeElement(match[1].toLowerCase(), match[2], sourceLabel));
    cursor = tagPattern.lastIndex;
    match = tagPattern.exec(childrenText);
  }

  const tail = childrenText.slice(cursor).trim();
  if (tail !== "") {
    throw new Error(sourceLabel + " contains unsupported SVG content near: " + tail.slice(0, 40));
  }
  return elements;
}

function sanitizeElement(tagName, rawAttrs, sourceLabel) {
  const attrs = parseAttributes(rawAttrs, sourceLabel + " <" + tagName + ">");
  if (tagName === "path") {
    rejectUnknownAttributes(attrs, ALLOWED_PATH_ATTRIBUTES, sourceLabel + " <path>");
    return {
      tag: tagName,
      attrs: sanitizePathAttributes(attrs, sourceLabel)
    };
  }
  if (tagName === "rect") {
    rejectUnknownAttributes(attrs, ALLOWED_RECT_ATTRIBUTES, sourceLabel + " <rect>");
    return {
      tag: tagName,
      attrs: sanitizeRectAttributes(attrs, sourceLabel)
    };
  }
  throw new Error(sourceLabel + " contains unsupported SVG element: " + tagName);
}

function sanitizePathAttributes(attrs, sourceLabel) {
  const className = sanitizeClass(attrs.class, sourceLabel);
  const d = attrs.d;
  if (typeof d !== "string" || d.trim() === "") {
    throw new Error(sourceLabel + " path must include d.");
  }
  if (!/^[MmZzLlHhVvCcSsQqTtAa0-9,\s.+-]+$/.test(d)) {
    throw new Error(sourceLabel + " path data contains unsupported characters.");
  }
  return {
    className: className,
    d: d.trim()
  };
}

function sanitizeRectAttributes(attrs, sourceLabel) {
  const sanitized = {
    className: sanitizeClass(attrs.class, sourceLabel),
    x: requiredNumber(attrs.x, sourceLabel + " rect.x"),
    y: requiredNumber(attrs.y, sourceLabel + " rect.y"),
    width: requiredPositiveNumber(attrs.width, sourceLabel + " rect.width"),
    height: requiredPositiveNumber(attrs.height, sourceLabel + " rect.height")
  };
  if (attrs.rx !== undefined) {
    sanitized.rx = requiredNumber(attrs.rx, sourceLabel + " rect.rx");
  }
  if (attrs.ry !== undefined) {
    sanitized.ry = requiredNumber(attrs.ry, sourceLabel + " rect.ry");
  }
  return sanitized;
}

function sanitizeClass(value, sourceLabel) {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(sourceLabel + " elements must include an allowed class.");
  }
  const classes = value.trim().split(/\s+/);
  classes.forEach(function validateClass(className) {
    if (!ALLOWED_CLASSES.has(className)) {
      throw new Error(sourceLabel + " uses unsupported class: " + className);
    }
  });
  return classes.join(" ");
}

function parseAttributes(rawAttrs, sourceLabel) {
  const attrs = {};
  const attrPattern = /([A-Za-z_:][A-Za-z0-9_:.-]*)\s*=\s*"([^"]*)"/g;
  let cursor = 0;
  let match = attrPattern.exec(rawAttrs);

  while (match) {
    const gap = rawAttrs.slice(cursor, match.index).trim();
    if (gap !== "") {
      throw new Error(sourceLabel + " contains unsupported attribute syntax near: " + gap);
    }
    if (attrs[match[1]] !== undefined) {
      throw new Error(sourceLabel + " repeats attribute: " + match[1]);
    }
    attrs[match[1]] = match[2];
    cursor = attrPattern.lastIndex;
    match = attrPattern.exec(rawAttrs);
  }

  const tail = rawAttrs.slice(cursor).trim();
  if (tail !== "") {
    throw new Error(sourceLabel + " contains unsupported attribute syntax near: " + tail);
  }
  return attrs;
}

function rejectUnknownAttributes(attrs, allowed, sourceLabel) {
  Object.keys(attrs).forEach(function reject(name) {
    if (!allowed.has(name)) {
      throw new Error(sourceLabel + " uses unsupported attribute: " + name);
    }
  });
}

function parseViewBox(value, sourceLabel) {
  if (typeof value !== "string") {
    throw new Error(sourceLabel + " must include a viewBox.");
  }
  const values = value.trim().split(/\s+/).map(Number);
  if (values.length !== 4 || values.some(function invalid(number) {
    return !Number.isFinite(number);
  })) {
    throw new Error(sourceLabel + " viewBox must contain four finite numbers.");
  }
  if (values[2] <= 0 || values[3] <= 0) {
    throw new Error(sourceLabel + " viewBox width and height must be positive.");
  }
  return {
    x: values[0],
    y: values[1],
    width: values[2],
    height: values[3]
  };
}

function requiredNumber(value, name) {
  const number = Number(value);
  if (!Number.isFinite(number)) {
    throw new Error(name + " must be a finite number.");
  }
  return number;
}

function requiredPositiveNumber(value, name) {
  const number = requiredNumber(value, name);
  if (number <= 0) {
    throw new Error(name + " must be positive.");
  }
  return number;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runCli().catch(function handleError(error) {
    console.error(error.message);
    process.exitCode = 1;
  });
}
