server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
